### PR TITLE
Relax activesupport dependency to support Rails 5

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by cbeer** [comment]
👏  thanks for getting this merged. I hope we get a new release with this soon?

**Comment by akzhan** [comment]
Yep, in 20 hours.

2016-10-25 23:06 GMT+03:00 Chris Beer <notifications@github.com>:

**Comment by cbeer** [comment]
Wonderful, thank you.

**Comment by cbeer** [comment]
Sorry to nag -- any update on the release schedule for this?

**Comment by KeithYJohnson** [comment]
Does anyone have this working with activesupport 5?  I pointed my gemfile at bluepill's master branch and am getting the following error:

```
/usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/rubygems/specification.rb:2285:in `raise_if_conflicts': Unable to activate bluepill-0.1.2, because activesupport-5.0.2 conflicts with activesupport (< 5, >= 3.2) (Gem::ConflictError)
	from /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/rubygems/specification.rb:1408:in `activate'
	from /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/rubygems.rb:196:in `rescue in try_activate'
	from /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/rubygems.rb:193:in `try_activate'
	from /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from /Users/keithjohnson/play/fleet/models/vehicle.rb:1:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from /Users/keithjohnson/play/fleet/vehicle.rb:3:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from test.rb:1:in `<main>'
```

**Comment by akzhan** [comment]
Just released 0.1.3

**Pull request merged**
